exclude:
  - 'app/_scss/components/_syntax.scss'
  - 'app/_bower_components/**'

linters:
  SelectorFormat:
    convention: hyphenated_BEM
  StringQuotes:
    style: double_quotes
  LeadingZero:
    style: include_zero
  QualifyingElement:
    allow_element_with_attribute: true
  PropertySortOrder:
    order: []
