# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: davidchin
title: David Chin
description: "I am a developer, specialising in front-end web and native application development."
author:
  name: David Chin
  email: davidchin.yf@gmail.com
  phone: +61 416 935 889

# URL
url: http://davidchin.me

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: kramdown
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

# Use Pygments to highlight code blocks
highlighter: pygments

# Default post path style
permalink: /blog/:title/

# Gems
gems:
  - jekyll-redirect-from
