title: David Chin - Software Engineer
email: davidchin.yf@gmail.com
description: The personal website of David Chin
url: "http://davidchin.me"
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock
gems:
    - jekyll-assets
assets:
    features:
        automatic_img_size: false
